# Generated by Django 5.2.2 on 2025-07-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Finishes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('LIVING_ROOM', 'Living Room Furniture'), ('BEDROOM', 'Bedroom Furniture'), ('DINING', 'Dining Room Furniture'), ('KITCHEN', 'Kitchen Furniture'), ('OUTDOOR', 'Outdoor Furniture'), ('OFFICE', 'Office Furniture'), ('STORAGE', 'Storage Furniture')], default='LIVING_ROOM', max_length=50)),
                ('material', models.CharField(choices=[('WOOD', 'Wood'), ('METAL', 'Metal'), ('PLASTIC', 'Plastic'), ('FABRIC', 'Fabric'), ('GLASS', 'Glass'), ('COMPOSITE', 'Composite Wood'), ('MIXED', 'Mixed Materials')], default='WOOD', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_assembly', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finishes', models.ManyToManyField(blank=True, to='furniture_app.finish')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
