# Generated by Django 5.2.2 on 2025-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='finishes',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LIVING_ROOM', 'Living Room'), ('BEDROOM', 'Bedroom'), ('DINING_ROOM', 'Dining Room'), ('OFFICE', 'Office'), ('OUTDOOR', 'Outdoor')], default='LIVING_ROOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('WOOD', 'Wood'), ('METAL', 'Metal'), ('FABRIC', 'Fabric'), ('PLASTIC', 'Plastic'), ('GLASS', 'Glass')], default='WOOD', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_assembly',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Finish',
        ),
    ]
