# Generated by Django 5.2.2 on 2025-07-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g., 10.50 for 10.5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SaleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_message', models.CharField(blank=True, help_text='Optional: A custom message for the banner. If empty, a default message will be used.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one SaleBanner can be active at a time. Deactivate others to activate this one.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_product', models.OneToOneField(help_text='Select the product to feature on the homepage banner.', on_delete=django.db.models.deletion.CASCADE, to='furniture_app.product')),
            ],
            options={
                'verbose_name': 'Sale Banner Configuration',
                'verbose_name_plural': 'Sale Banner Configurations',
            },
        ),
    ]
