# Generated by Django 5.2.2 on 2025-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0007_product_discount_percentage_product_on_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salebanner',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, help_text='Optional: Date and time when the sale on this banner ends. Leave blank for no end date.', null=True),
        ),
    ]
